### ISSUE TITLE
Comentarios avance 1

### ISSUE THREAD

**Issue by AzaleaGuerra** [Amanecer1/Trabajo-Final_Bioinfo2017#1]
Suena padre que uses datos simulados, sin embargo, no podrás convertir a formatos fastq porque éste lleva información de la calidad de la secuencia, información que obtienes del secuenciador. Además, no tendrás datos de profundidad (depth). Ten en cuenta esto cuando ensambles. 
Ya que probablemente sólo tendrás un individuo de cada especie, no podrás hacer análisis de diversidad, pero quizá podrías hacer comparaciones entre los genomas y tratar de ver si hay regiones que difieren más.

**Comment by Amanecer1** [comment]
Gracias por aclararme lo de el formato fastq, estoy de acuerdo. También, estaba buscando si hay alguna otra aplicación en la que pueda utilizar la simulación en otro programa para ensamblar genomas y realizar el análisis. Retomando tu último punto, había pensado que podría buscar regiones que se sepan virulentas y comparar entre especies de Treponema (hay especies que son patogénicas y otras no). Ojalá, sigamos en comunicación.

**Comment by Amanecer1** [comment]
Corregí en el md:
1. La redacción de RAD's a loci RAD
2. Borré el renglón donde propongo convertir de formato tipo fasta a fastq
3. Pensando en que podría tener algunos problemas en pyrad en el ensamblaje, añadí una alternativa, hacer la simulación en el programa SiLICO.

**Comment by AzaleaGuerra** [comment]
Suena muy bien comparar regiones asociadas a virulencia. No he usado el programa SiLICO, pero ya nos contarás cómo te fue y qué te funcionó mejor.

**Comment by Amanecer1** [comment]
Ok. Gracias
